# Generated by Django 5.1.6 on 2025-02-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
