# Generated by Django 5.1.6 on 2025-02-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_alter_profile_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_doj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emp_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emp_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emp_passw',
            field=models.CharField(max_length=100),
        ),
    ]
