# Generated by Django 5.1.6 on 2025-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_alter_profile_emp_doj_alter_profile_emp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
