# Generated by Django 5.1.6 on 2025-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
