# Generated by Django 5.1.6 on 2025-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=30)),
                ('quantity', models.IntegerField(max_length=500)),
            ],
        ),
    ]
