# Generated by Django 5.1.6 on 2025-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questpaperapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='qno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
